# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 1233)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 471, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_sort = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_sort.setObjectName("label_sort")
        self.gridLayout.addWidget(self.label_sort, 1, 0, 1, 1)
        self.label_id = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_id.setObjectName("label_id")
        self.gridLayout.addWidget(self.label_id, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.line_id = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_id.setObjectName("line_id")
        self.gridLayout.addWidget(self.line_id, 0, 1, 1, 1)
        self.line_sort = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_sort.setObjectName("line_sort")
        self.gridLayout.addWidget(self.line_sort, 1, 1, 1, 1)
        self.line_obzar = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_obzar.setObjectName("line_obzar")
        self.gridLayout.addWidget(self.line_obzar, 2, 1, 1, 1)
        self.line_vibor = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_vibor.setObjectName("line_vibor")
        self.gridLayout.addWidget(self.line_vibor, 3, 1, 1, 1)
        self.line_descr = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_descr.setObjectName("line_descr")
        self.gridLayout.addWidget(self.line_descr, 4, 1, 1, 1)
        self.line_price = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_price.setObjectName("line_price")
        self.gridLayout.addWidget(self.line_price, 5, 1, 1, 1)
        self.line_volume = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_volume.setObjectName("line_volume")
        self.gridLayout.addWidget(self.line_volume, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.new_or_change = QtWidgets.QPushButton(parent=self.centralwidget)
        self.new_or_change.setGeometry(QtCore.QRect(130, 610, 271, 61))
        self.new_or_change.setObjectName("new_or_change")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "описание вкуса"))
        self.label_1.setText(_translate("MainWindow", "степень обжарки"))
        self.label_2.setText(_translate("MainWindow", " молотый/в зернах"))
        self.label_sort.setText(_translate("MainWindow", "название сорта"))
        self.label_id.setText(_translate("MainWindow", "ID"))
        self.label_5.setText(_translate("MainWindow", "объем"))
        self.label_4.setText(_translate("MainWindow", "цена"))
        self.new_or_change.setText(_translate("MainWindow", "Добавить или изменить существующий"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
